In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import selenium
from selenium import webdriver
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By # 셀레니움 4.0부터 포함된 함수(필수)
import os
import sys
import urllib.request
from urllib import parse
import ssl
from selenium.webdriver.support.ui import Select

In [6]:
wine_flavor = pd.read_csv('wine_character.csv')
wine_flavor

     Unnamed: 0  당도  바디  산도  타닌
0             0   1   3   3   3
1             1   1   3   3   2
2             2   2   4   3   1
3             3   1   4   3   3
4             4   4   2   4   3
..          ...  ..  ..  ..  ..
405         405   1   3   4   4
406         406   1   4   4   4
407         407   1   3   3   1
408         408   1   4   4   5
409         409   1   3   3   2

[410 rows x 5 columns]

In [8]:
wine_flavor = wine_flavor.drop(['Unnamed: 0'],axis=1)

In [9]:
wine_flavor.index=wine_flavor.index + 1
wine_flavor.head() # id값 설정

   당도  바디  산도  타닌
1   1   3   3   3
2   1   3   3   2
3   2   4   3   1
4   1   4   3   3
5   4   2   4   3

In [15]:
wine_flavor = wine_flavor.drop([402,403,404,405,406,407,408,409,410])

In [16]:
wine_flavor

     당도  바디  산도  타닌
1     1   3   3   3
2     1   3   3   2
3     2   4   3   1
4     1   4   3   3
5     4   2   4   3
..   ..  ..  ..  ..
396   1   4   2   1
397   1   3   4   5
398   1   4   1   1
399   1   4   1   1
400   1   4   1   1

[400 rows x 4 columns]

In [17]:
wine_flavor.to_csv('./wine400_flavor.csv', encoding = 'utf-8-sig')

In [22]:
wine_flavor=pd.read_csv('wine400_flavor.csv',encoding='utf-8-sig')

In [23]:
wine_flavor

     Unnamed: 0  당도  바디  산도  타닌
0             1   1   3   3   3
1             2   1   3   3   2
2             3   2   4   3   1
3             4   1   4   3   3
4             5   4   2   4   3
..          ...  ..  ..  ..  ..
395         396   1   4   2   1
396         397   1   3   4   5
397         398   1   4   1   1
398         399   1   4   1   1
399         400   1   4   1   1

[400 rows x 5 columns]

In [24]:
wine_flavor = wine_flavor.rename(columns={'Unnamed: 0':'id'}) # 컬럼명 변경 
wine_flavor

      id  당도  바디  산도  타닌
0      1   1   3   3   3
1      2   1   3   3   2
2      3   2   4   3   1
3      4   1   4   3   3
4      5   4   2   4   3
..   ...  ..  ..  ..  ..
395  396   1   4   2   1
396  397   1   3   4   5
397  398   1   4   1   1
398  399   1   4   1   1
399  400   1   4   1   1

[400 rows x 5 columns]

In [25]:
wine_df = pd.read_csv("wine400_fin.csv")
wine_df

,id,주종,중분류,상품명,생산국가,생산자,주요품종,도수,음용온도,추천음식
0,1,wine,레드,"7 컬러즈, '그랑 리제르바' 카베르네 소비뇽 뮈스카",칠레,세븐 컬러즈 7 Colores,"카베르네 소비뇽 (Cabernet Sauvignon) 95%, 뮈스까 (Muscat...",13.5,16~18 ℃,"채끝 스테이크, 크림 파스타, 블루치즈 버거 등과 잘 어울린다."
1,2,wine,레드,"GCF, 꼬뜨 드 뵈프",프랑스,GCF 그룹 GCF Group,"시라/쉬라즈 (Syrah/Shiraz) , 마르셀란 (Marselan)",13.0,16~18 ℃,"뵈프 부르기뇽, 안심 찹 스테이크, 로스트 비프 스테이크 등과 잘 어울린다."
2,3,wine,화이트,"가트, 리슬링",호주,가트 와인즈 Gatt Wines,리슬링 (Riesling) 100%,11.5,10~12 ℃,"샐러드, 해산물, 치즈 등과 잘 어울린다."
3,4,wine,레드,갈로 리빙스톤 콩코드,미국,갤로 패밀리 빈야드 Gallo Family Vineyard - E&J Gallo W...,콩코드 (Concord),11.0,14~16 ℃,"소시지, 육포, 떡볶이, 순대, 튀김, 족발, 만두, 자장면 등과 잘 어울린다."
4,5,wine,주정강화,글로리아 토니 포트 와인,포르투갈,빈센테 파리아 비뉴스 Vincente Faria VInhos,"틴타 로리즈 (Tinta Roriz) , 투리가 프란카 (Touriga Franca...",20.0,14~16 ℃,"리코타, 크림치즈, 말린과일, 케이크, 초콜렛 등 디저트와 잘 어울린다."
...,...,...,...,...,...,...,...,...,...,...
395,396,wine,레드,"매티스, 그르나슈",미국,매티스 와이너리 Mathis Winery,"그르나슈 (Grenache) 82%, 까리냥 (Carignan/Carignane) ...",14.0,16~18 ℃,"덩어리 째 오븐에 구운 육류와 햄, 스테이크, 라자냐, 치즈 등과 잘 어울린다."
396,397,wine,화이트,"메종 카스텔, 소비뇽 블랑",프랑스,메종 카스텔 Maison Castel,소비뇽 블랑 (Sauvignon Blanc),13.0,8~10 ℃,"연어 타르타르 스테이크와 같은 해산물 요리, 샐러드와 같은 야채, 생선 그릴 요리와..."
397,398,wine,스파클링,"메종 카스텔, 퀴베 블랑쉬 브뤼",프랑스,메종 카스텔 Maison Castel,샤르도네 (Chardonnay),11.0,6~8 ℃,"디저트, 조개, 생선 요리 또는 반주와 잘 어울린다."
398,399,wine,화이트,"메종 카스텔, 푸이 퓌메",프랑스,메종 카스텔 Maison Castel,소비뇽 블랑 (Sauvignon Blanc),13.0,8~10 ℃,"샤프란을 곁들인 생선 스튜 요리 등 생선, 갑각류, 조개 요리, 크림 소스를 곁들인..."
399,400,wine,화이트,"멜쉐이머, 리슬링 파인헤릅",독일,바인굿 멜쉐이머 Weingut Melsheimer,리슬링 (Riesling) 100%,10.5,8~10 ℃,"베이컨, 꼬치구이, 해산물, 양념치킨, 하몽, 살라미, 아시아요리, 매운음식, 동남..."

In [26]:
merge_wine = pd.merge(wine_df,wine_flavor, how='outer',on='id')
merge_wine

,id,주종,중분류,상품명,생산국가,생산자,주요품종,도수,음용온도,추천음식,당도,바디,산도,타닌
0,1,wine,레드,"7 컬러즈, '그랑 리제르바' 카베르네 소비뇽 뮈스카",칠레,세븐 컬러즈 7 Colores,"카베르네 소비뇽 (Cabernet Sauvignon) 95%, 뮈스까 (Muscat...",13.5,16~18 ℃,"채끝 스테이크, 크림 파스타, 블루치즈 버거 등과 잘 어울린다.",1,3,3,3
1,2,wine,레드,"GCF, 꼬뜨 드 뵈프",프랑스,GCF 그룹 GCF Group,"시라/쉬라즈 (Syrah/Shiraz) , 마르셀란 (Marselan)",13.0,16~18 ℃,"뵈프 부르기뇽, 안심 찹 스테이크, 로스트 비프 스테이크 등과 잘 어울린다.",1,3,3,2
2,3,wine,화이트,"가트, 리슬링",호주,가트 와인즈 Gatt Wines,리슬링 (Riesling) 100%,11.5,10~12 ℃,"샐러드, 해산물, 치즈 등과 잘 어울린다.",2,4,3,1
3,4,wine,레드,갈로 리빙스톤 콩코드,미국,갤로 패밀리 빈야드 Gallo Family Vineyard - E&J Gallo W...,콩코드 (Concord),11.0,14~16 ℃,"소시지, 육포, 떡볶이, 순대, 튀김, 족발, 만두, 자장면 등과 잘 어울린다.",1,4,3,3
4,5,wine,주정강화,글로리아 토니 포트 와인,포르투갈,빈센테 파리아 비뉴스 Vincente Faria VInhos,"틴타 로리즈 (Tinta Roriz) , 투리가 프란카 (Touriga Franca...",20.0,14~16 ℃,"리코타, 크림치즈, 말린과일, 케이크, 초콜렛 등 디저트와 잘 어울린다.",4,2,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,wine,레드,"매티스, 그르나슈",미국,매티스 와이너리 Mathis Winery,"그르나슈 (Grenache) 82%, 까리냥 (Carignan/Carignane) ...",14.0,16~18 ℃,"덩어리 째 오븐에 구운 육류와 햄, 스테이크, 라자냐, 치즈 등과 잘 어울린다.",1,4,2,1
396,397,wine,화이트,"메종 카스텔, 소비뇽 블랑",프랑스,메종 카스텔 Maison Castel,소비뇽 블랑 (Sauvignon Blanc),13.0,8~10 ℃,"연어 타르타르 스테이크와 같은 해산물 요리, 샐러드와 같은 야채, 생선 그릴 요리와...",1,3,4,5
397,398,wine,스파클링,"메종 카스텔, 퀴베 블랑쉬 브뤼",프랑스,메종 카스텔 Maison Castel,샤르도네 (Chardonnay),11.0,6~8 ℃,"디저트, 조개, 생선 요리 또는 반주와 잘 어울린다.",1,4,1,1
398,399,wine,화이트,"메종 카스텔, 푸이 퓌메",프랑스,메종 카스텔 Maison Castel,소비뇽 블랑 (Sauvignon Blanc),13.0,8~10 ℃,"샤프란을 곁들인 생선 스튜 요리 등 생선, 갑각류, 조개 요리, 크림 소스를 곁들인...",1,4,1,1
399,400,wine,화이트,"멜쉐이머, 리슬링 파인헤릅",독일,바인굿 멜쉐이머 Weingut Melsheimer,리슬링 (Riesling) 100%,10.5,8~10 ℃,"베이컨, 꼬치구이, 해산물, 양념치킨, 하몽, 살라미, 아시아요리, 매운음식, 동남...",1,4,1,1

In [27]:
merge_wine.to_csv('./wine400.csv', encoding = 'utf-8-sig',index=False)